### ISSUE TITLE
Modification are not implemented in "Quality" section

### ISSUE THREAD

**Issue by SanaBenKhadher** [famaridon/hugo-clear-guide#1]
**Describe the bug**
I did modification in "Quality" section and commit update.
Pipeline "doc-private" is correctly launched (#20240220.1 • update) but modification are not updated in the interface.

![image](https://github.com/famaridon/hugo-clear-guide/assets/160590943/abeefa79-c15a-4fa2-bd08-a81ab442d240)

**Screenshots**

**Comment by famaridon** [comment]
Fixed in CI
